raw = open("data/enwik8_1KB.txt","rb").read()
dec = open("data/enwik8_1KB.dec.txt","rb").read()
n = min(len(raw), len(dec))
diff_at = next((i for i in range(n) if raw[i] != dec[i]), n)
print(f"第一次不同发生在第 {diff_at} 字节")
print(f"原文该位置附近: {repr(raw[max(0,diff_at-20):diff_at+20])}")
print(f"解压该位置附近: {repr(dec[max(0,diff_at-20):diff_at+20])}")
print()
print(f"原文末尾 30 字节: {repr(raw[-30:])}")
print(f"解压末尾 30 字节: {repr(dec[-30:])}")
